version: '3.4'

services:
  digiinv.api:
    image: ${DOCKER_REGISTRY-}digiinvapi
    build:
      context: .
      dockerfile: DigiInv.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
